name: Train Transformers

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger

jobs:
  setup-and-train:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert  # Needed if running notebooks

    # Step 4: Run GPT training
    - name: Train GPT
      run: |
        jupyter nbconvert --to notebook --execute build_gpt.ipynb --output /dev/null

    # Step 5: Run BERT training
    - name: Train BERT
      run: |
        jupyter nbconvert --to notebook --execute build_bert.ipynb --output /dev/null

   
    # Step 6: Upload model artifacts
    - name: Upload checkpoints
      uses: actions/upload-artifact@v4
      with:
        name: trained_models
        path: checkpoints/*
