name: Train Transformers

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger

jobs:
  setup-and-train:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Download any dataset if needed
    # (Optional)
    #- name: Download dataset
    #  run: python scripts/download_dataset.py

    # Step 5: Build & Train BERT
    - name: Build & Train BERT
      run: |
        jupyter nbconvert --to script scripts/build_bert.ipynb --stdout | python

    # Step 6: Build & Train GPT
    - name: Build & Train GPT
      run: |
        jupyter nbconvert --to script scripts/build_gpt.ipynb --stdout | python

    # Step 7: Upload model artifacts
    - name: Upload model checkpoints
      uses: actions/upload-artifact@v4
      with:
        name: checkpoints
        path: checkpoints/*
